### ISSUE TITLE
Force calculation failing for Nequip due to no grad function

### ISSUE THREAD

**Issue by jvita** [jvita/ip_explorer#1]
Moving jvita/data_efficiency_in_IAPS#1 to this repo, which should be used for the ip_explorer code, as opposed to https://github.com/jvita/data_efficiency_in_IAPS, which is for the paper data.

I will remove the `ip_explorer` code from the other repo to avoid future confusion.

Copy of original issue text:

> I am attempting to generate a loss landscape for a Nequip model I have trained by running "ip_explorer/landscape/main.py". When ip_explorer/models/nequip.py attempts to make a forward pass through the network in the compute_loss function, the following error arises: "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn".
> 
> This is occurring because the "total_energy" output field of the model for some reason did not record the gradient history of the forward pass. Therefore when we try to differentiate the energy with torch.autograd.grad to calculate forces, there is an error.
> 
> I have verified that this same model can correctly calculate forces and perform MD simulation in my own codebases.
> 
> The command I am running is this:
> python main.py
> --num-nodes=1
> --save-dir /home/sanjeevr/implicit-md/landscapes
> --model-type=nequip --database-path=/home/sanjeevr/MDsim/MODELPATH/nequip/md17-aspirin_10k_nequip
> --model-path=/home/sanjeevr/MDsim/MODELPATH/nequip/md17-aspirin_10k_nequip
> --landscape-type=plane
> --no-compute-initial-losses
> --steps=10
> 
> Any ideas on why this may be occurring? I think it could be due to the way the model is being wrapped in the SimpleModelWrapper. Could it be that I'm not passing in other necessary command line arguments?

@jeevster, can you try re-running your script using the main branch of this repo?

**Comment by jeevster** [comment]
Thanks. I re-ran the script using the main branch of this repo and the same issue persists.
Some more context that could be relevant.
I had to make the following changes to ip_explorer/landscape/__main__.py to get the code to run up to the point where it failed.
1. Remove the layers input to SimpleModelWrapper (i.e only pass in model instead of model and layers) [here](https://github.com/jvita/ip_explorer/blob/main/ip_explorer/landscape/__main__.py#L246C48-L246C48) and [here](https://github.com/jvita/ip_explorer/blob/main/ip_explorer/landscape/__main__.py#L229)
2. Remove the n_loss_terms = 2 argument from the random_plane function [here](https://github.com/jvita/ip_explorer/blob/main/ip_explorer/landscape/__main__.py#L307)

I am wondering if change 1 is inadvertently changing something about the model so that gradient history is not tracked during the forward pass.

I am using version 3.0.6 of loss-landscapes, version 1.13.1 of pytorch, and version 2.1.0 of pytorch-lightning.

**Comment by jvita** [comment]
It looks like I forgot that we had patched loss-landscapes to be more efficient and to handle computing energy/force landscapes at the same time. This probably explains why you had to make the patches that you described to `ip_explorer` just to get it to run.

Can you try installing the patched version of [loss-landscapes](https://github.com/jvita/ip_explorer/tree/main/patches/loss_landscapes), then running your code again (after un-doing your modifications to `ip_explorer`)?

Sorry for these issues -- you're the first one using the code outside of our team, so I appreciate your patience as we sort these out.

**Comment by jeevster** [comment]
Ok, I installed the patched version of loss-landscapes and undid my modifications to ip_explorer. The code now runs without my modifications, but I'm still getting the same gradient error with the Nequip model forward pass. Full stack trace below:
```Traceback (most recent call last):
  File "/home/sanjeevr/implicit-md/ip_explorer/ip_explorer/landscape/__main__.py", line 356, in <module>
    main()
  File "/home/sanjeevr/implicit-md/ip_explorer/ip_explorer/landscape/__main__.py", line 302, in main
    loss_data_fin = loss_landscapes.random_plane(
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/loss_landscapes/main.py", line 315, in random_plane
    print("Verifying initial losses:", metric(model_start_wrapper))
  File "/home/sanjeevr/implicit-md/ip_explorer/ip_explorer/landscape/loss.py", line 57, in __call__
    self.evaluation_fxn(model_wrapper.modules[0], self.data_loader)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 755, in test
    return call._call_and_handle_interrupt(
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 795, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1029, in _run_stage
    return self._evaluation_loop.run()
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 391, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 416, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/home/sanjeevr/implicit-md/ip_explorer/ip_explorer/models/base.py", line 342, in test_step
    for k,v in fxn(batch).items():
  File "/home/sanjeevr/implicit-md/ip_explorer/ip_explorer/models/nequip.py", line 103, in compute_loss
    out = self.model.forward(batch_dict)
  File "/home/sanjeevr/.local/lib/python3.9/site-packages/nequip/nn/_rescale.py", line 140, in forward
    data = self.model(data)
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sanjeevr/.local/lib/python3.9/site-packages/nequip/nn/_grad_output.py", line 83, in forward
    grads = torch.autograd.grad(
  File "/home/sanjeevr/mambaforge/envs/mdsim2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn```

**Comment by jvita** [comment]
Can you try adding the argument `inference_mode=False` to the `pl.Trainer` constructor ([here](https://github.com/jvita/ip_explorer/blob/91b798a7ad5afca9f631e9bd7366831fdf631910/ip_explorer/landscape/__main__.py#L163C8-L163C8) and [here](https://github.com/jvita/ip_explorer/blob/91b798a7ad5afca9f631e9bd7366831fdf631910/ip_explorer/landscape/__main__.py#L276))? I believe this issue is being caused by a change in how PyTorch lightning handles gradients during testing/validation -- I had to patch it previously, but I think it's been formally fixed in newer versions of PyTorch Lightning.

**Comment by jeevster** [comment]
Ah, that appears to have fixed the no grad issue! 
However, it seems like the evaluation_fxn is not populating the model wrapper with results. Specifically, [here](https://github.com/jvita/ip_explorer/blob/main/ip_explorer/landscape/loss.py#L60) it looks like model_wrapper.modules[0].results is an empty dictionary. Not sure why that's happening since I verified the loss is being computed and returned [here](https://github.com/jvita/ip_explorer/blob/main/ip_explorer/models/nequip.py#L98).

**Comment by jvita** [comment]
> Ah, that appears to have fixed the no grad issue!

Glad to hear it! I've pushed an update to `main` that adds this flag.

> However, it seems like the evaluation_fxn is not populating the model wrapper with results.

This looks like it again may be due to a change in PytorchLighting, this time with how it handles `on_test_epoch_end` (for my future reference, see [this PL issue](https://github.com/Lightning-AI/lightning/discussions/17182#discussioncomment-5536583)). I've also updated this and added it to the newest commit.

Can you try pulling from `main` again and re-running your code?

**Comment by jeevster** [comment]
That seems to have fixed it! Looks like the landscape generation code is running now, and based on the progress so far seems like it will take around 2 hours to complete (I'm running on a single A6000 GPU with 32 workers in the dataloader). Does that seem reasonable? And do you have any guidelines on a reasonable value for the --steps argument taken in by the landscape generating functions? I currently have steps set to 10, but not sure if that's a reasonable value here.

**Comment by jvita** [comment]
> That seems to have fixed it!

Awesome, I'm glad we were able to sort it out. Thanks for your help and patience.

With regards to the runtime:
* Every point in your landscape requires evaluating the entire dataset. So if you're computing a 2D landscape for your training set, the total cost will be `steps*steps*cost_per_epoch`. It's expensive, and there's no obvious workaround other than adding more GPUs if you can. 2 hours doesn't surprise me.
* The number of workers in the dataloader likely won't be the bottleneck -- I'd be shocked if I/O were slower than a NequIP forward pass.
* I'd recommend keeping `steps` relatively low to start off (10 is fine) while you tune `distance` to your desired magnitude, then increase `steps` slowly until you achieve the resolution that you want.

I would _highly_ recommend doing 1D landscapes (`--landscape-type 'lines'` ) rather than 2D. We found that this usually told us everything that we needed to know (curvature) about the topography of the minimum, and only scales in cost as O(steps) rather than O(steps^2). 2D is cool to look at, and can help you make sure you aren't missing any topographical features in the 1D plots, but they're too expensive to use for systematic analysis.

**Comment by jeevster** [comment]
This is very helpful, thanks. What is `distance` in this context? Is it the norm of the maximum parameter perturbation used in the landscape? And so `steps` is the number of discretization points between 0 perturbation and `distance`?

**Comment by jvita** [comment]
Yes, your explanations of both `distance` and `steps` are correct.

**Comment by jeevster** [comment]
Cool thanks. I see that there is [code](https://github.com/jvita/data_efficiency_in_IAPS/blob/main/data/02_LossLandscapes_NequIP.ipynb) in the other repo to analyze the loss landscapes (e.g calculate entropy, etc.). Is that code functional/up-to-date, and if so, would it be possible to move that code to this repo as well?

**Comment by jvita** [comment]
Yes, that code should be up to date. I'd prefer to leave all of those notebooks in the other repo, as they're what were used to generate the actual figures in the paper. However, I'll think about replicating some minimal examples to this repo when I find the time.

**Comment by jvita** [comment]
I'm going to go ahead and close this issue now -- feel free to either re-open it, or open a new one, if you have any further questions.
